### ISSUE TITLE
Addon manager crashes with a clean install

### ISSUE THREAD

**Issue by SavtechSolutions** [fmmmlee/GW2-Addon-Manager#113]
Attached config.txt is really config.xml, but GitHub doesn't allow XML attachments

![Capture](https://user-images.githubusercontent.com/20711595/120106909-dfa84200-c12c-11eb-8f92-879427090b86.PNG)
[config.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/6566289/config.txt)
[log.txt](https://github.com/fmmmlee/GW2-Addon-Manager/files/6566291/log.txt)

Crashes upon loading (screenshot). Chose a "revert to a clean install" option previously, now can't even get to that screen anymore.

**Comment by SavtechSolutions** [comment]
Log file contains peculiar lines:

> The remote server returned an error: (403) Forbidden.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\Backend\Addons\ApprovedList.cs:line 34
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\Backend\Addons\ApprovedList.cs:line 86
   at GW2_Addon_Manager.OpeningViewModel..ctor() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\UI\OpeningPage\OpeningViewModel.cs:line 222
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\UI\OpeningPage\OpeningViewModel.cs:line 237
   at GW2_Addon_Manager.OpeningView..ctor() in C:\Users\Matthew Lee\Documents\GitHub\GW2-UOAOM-Git\application\GW2 Addon Manager\UI\OpeningPage\OpeningView.xaml.cs:line 31

Why is it accessing C:\Users\Matthew Lee\?

**Comment by SleepyZeez** [comment]
Someone else had the same issue, it's a github issue. Just have to wait a bit.
[Critical Error when Launching #109](https://github.com/fmmmlee/GW2-Addon-Manager/issues/109#issuecomment-846287008)

**Comment by SavtechSolutions** [comment]
What does it need the GitHub for? I understand that it checks it for the updates of installed modules, but I'd think that should happen after the UI is loaded, not before?

**Comment by SavtechSolutions** [comment]
Overall, I don't think this is just a "GitHub issue" - if there's a rate limit on GitHub, the app should handle that error instead of crashing (and maybe also limit GitHub access to only the absolute necessities)
