### ISSUE TITLE
Remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by 10045250** [fmmmlee/GW2-Addon-Manager#219]
### Please attach a copy of config.yaml or config.ini to the issue.

**Describe the bug**
When I launch the add-on manager, it returns a Github API Error that says:
```
Github servers returned an error; please try again in a few minutes.
The error was: The remote server returned an error: (403) Forbidden.
```

**To Reproduce**
Download the add-on manager > Extract the ZIP file > Click on the GW2 add-on manager application > Wait for it to load . . . then the pop-up comes up with the error message.

**Additional context**

**don't forget to attach the config file to the issue**
I don't know what that is. I just downloaded the file, tried to run the installation application, and got the error above.

**Comment by LinearBotSystems** [comment]
Same problem here the after update of the Addon-Manager I updated shorty it broke in middle of the update now only the same error. Sounds like an anti-scrapper stuff from GitHub.

**Comment by lholbert** [comment]
Any fix for this, I'm seeing this as well...

**Comment by Dechax** [comment]
Same problem, here is the log if it helps.

[log.txt](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/12514639/log.txt)

And here's the conifg converted to .txt.

[GW2 Addon Manager.exe.txt](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/12514676/GW2.Addon.Manager.exe.txt)

**Comment by kursion** [comment]
Same issue, after doing a reset all full clean this message appears

The logs: 
```
[Log Entry]
10/14/2023 10/14/2023 11:02:31 AM
The invocation of the constructor on type 'GW2_Addon_Manager.OpeningView' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverterCore(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter, Boolean isUnsafe)
   at System.Windows.Navigation.NavigationService.GetObjectFromResponse(WebRequest request, WebResponse response, Uri destinationUri, Object navState)
   at System.Windows.Navigation.NavigationService.DoNavigate(Uri source, NavigationMode f, Object navState)
   at System.Windows.Navigation.NavigateQueueItem.Dispatch(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
The remote server returned an error: (403) Forbidden.
   at GW2_Addon_Manager.UpdateHelpers.DownloadStringFromGithubAPI(WebClient wc, String url)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo()
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList()
   at GW2_Addon_Manager.OpeningViewModel..ctor()
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance()
   at GW2_Addon_Manager.OpeningView..ctor()
```

I am now unable to use the addon manager

**Comment by kursion** [comment]
Ah just read on another issue that might be caused by github having a hard limitation on the connection. Therefore, I need to wait 1h

**Comment by Psychotopia** [comment]
got the issue myself left me in a bit of a pickle reinstalled ark dps to see if it had updated for the latest patch it hadnt causes insta crashes, go to uninstall arkdps with manager its crashes with this issue
add way to uninstall addons without connecting to github?

**Comment by YangZA** [comment]
This is an error returned from the GitHub API and the author is unwilling to fix.

**Comment by Draeggiar** [comment]
I've fixed most of the 403 errors in latest release on my fork: [Addon Manager v1.4.0](https://github.com/Draeggiar/GW2-Addon-Manager/releases/tag/v1.4.0). Althouth Github API is limited to 300 requests per minute, so if you try hard enought you would still be able to break it.

**Comment by sigma67** [comment]
@Draeggiar getting the exact same error with your version. 403 (rate limit exceeded)
