### ISSUE TITLE
Crashes when run via Whisky.app on macOS

### ISSUE THREAD

**Issue by amckinlay** [fmmmlee/GW2-Addon-Manager#224]
GW2 Addon Manager.exe crashes upon launch with:

<img width="369" alt="Critical Error An Unhandled Exception Occurred. Exception from HRESULT: 0x88980406" src="https://github.com/gw2-addon-loader/GW2-Addon-Manager/assets/1351003/8c689d78-dcdf-46e4-b428-b9bc8b346336">

I tried launching it with Whisky.app 2.2.3 running WINE 7.7.

`log.txt`:
```
[Log Entry]
3/10/2024 3/10/2024 4:12:12 PM
Exception from HRESULT: 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

`GW2 Addon Manager.exe.config`:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="resources\plugins" />
      <dependentAssembly>
        <assemblyIdentity name="CommonServiceLocator" publicKeyToken="489b6accfaf20ef0" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.5.0" newVersion="2.0.5.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="YamlDotNet" publicKeyToken="ec19458f3c15af5e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by cheahjs** [comment]
Bug is likely out of scope of the project, but you can get past the error if you install the `d3dcompiler_47` dll via winetricks, but rendering is likely to be broken.

**Comment by amckinlay** [comment]
Why not include it?
