### ISSUE TITLE
Add error message when FetchListFromRepo fails.

### ISSUE THREAD

**Issue by mpaille** [fmmmlee/GW2-Addon-Manager#70]
When we restart the application a bunch of times in a row, the application crashes because we get a 403 from Github.

Here is the stack trace :
`   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at GW2_Addon_Manager.ApprovedList.FetchListFromRepo() in C:\Users\mapaille\source\repos\GW2-Addon-Manager\application\GW2 Addon Manager\Backend\Addons\ApprovedList.cs:line 34
   at GW2_Addon_Manager.ApprovedList.GenerateAddonList() in C:\Users\mapaille\source\repos\GW2-Addon-Manager\application\GW2 Addon Manager\Backend\Addons\ApprovedList.cs:line 86
   at GW2_Addon_Manager.OpeningViewModel..ctor() in C:\Users\mapaille\source\repos\GW2-Addon-Manager\application\GW2 Addon Manager\UI\OpeningPage\OpeningViewModel.cs:line 229
   at GW2_Addon_Manager.OpeningViewModel.get_GetInstance() in C:\Users\mapaille\source\repos\GW2-Addon-Manager\application\GW2 Addon Manager\UI\OpeningPage\OpeningViewModel.cs:line 244
   at GW2_Addon_Manager.OpeningView..ctor() in C:\Users\mapaille\source\repos\GW2-Addon-Manager\application\GW2 Addon Manager\UI\OpeningPage\OpeningView.xaml.cs:line 35`

**Comment by mpaille** [comment]
Duplicate of #20
